<?php
define('TABLE_ACCESS_PROFILES','access_profiles');
define('TABLE_ACCESS','access');
define('TABLE_ADDRESS_BOOK','address_book');
define('TABLE_ADMIN_GROUP','admin_group');
define('TABLE_ADMIN','admin');
define('TABLE_BRANCH','branch');
define('TABLE_CATEGORIES','categories');
define('TABLE_CONFIGURATION_GROUP','configuration_group');
define('TABLE_CONFIGURATION','configuration');
define('TABLE_COUPONS_REDEEM','coupons_redeem');
define('TABLE_COUPONS','coupons');
define('TABLE_CUSTOMERS_BASKET','customers_basket');
define('TABLE_CUSTOMERS_INFO','customers_info');
define('TABLE_CUSTOMERS','customers');
define('TABLE_INGREDIENTS','ingredients');
define('TABLE_BRANCH_OPENING_TIME','branch_opening_time');
define('TABLE_ORDER_PAYMENT','order_payment');
define('TABLE_ORDER_PRODUCTS','order_products');
define('TABLE_ORDER_STATUS_HISTORY','order_status_history');
define('TABLE_ORDER_STATUS','order_status');
define('TABLE_ORDER_TOTALS','order_totals');
define('TABLE_ORDER_TYPE','order_type');
define('TABLE_ORDERS_TO_BRANCH','orders_to_branch');
define('TABLE_ORDERS','orders');
define('TABLE_PAYMENT_METHOD','payment_method');
define('TABLE_PRODUCTS_TO_CATEGORIES','products_to_categories');
define('TABLE_PRODUCTS_TO_INGREDIENTS','products_to_ingredients');
define('TABLE_PRODUCTS','products');
define('TABLE_SPECIALS','specials');
define('TABLE_TESTIMONIALS_HISTORY','testimonials_history');
define('TABLE_TESTIMONIALS','testimonials');
define('TABLE_WHOS_ONLINE','whos_online');
define('TABLE_BRANCH_CLOSURE_DATES','branch_closure_dates');

?>
